import type {
  NextFunction,
  Request,
  Response,
} from "express";

import {
  env,
} from "../../config/env.js";

import {
  getCardRedirectContext,
} from "./redirect.service.js";

import {
  getOrCreateAnonymousVisitor,
} from "../interactions/anonymous-visitor.util.js";

import {
  getInteractionRequestMetadata,
} from "../interactions/request-metadata.util.js";

import {
  trackWithinBudget,
} from "../interactions/bounded-tracking.js";

type InteractionSource =
  | "NFC"
  | "QR"
  | "UNKNOWN";

function getInteractionSource(
  value:
    unknown
): InteractionSource {
  if (
    typeof value !==
    "string"
  ) {
    return "UNKNOWN";
  }

  const normalized =
    value
      .trim()
      .toLowerCase();

  if (
    normalized ===
    "nfc"
  ) {
    return "NFC";
  }

  if (
    normalized ===
    "qr"
  ) {
    return "QR";
  }

  return "UNKNOWN";
}

export async function redirectCardController(
  req:
    Request,

  res:
    Response,

  next:
    NextFunction
) {
  /*
   * =======================================================
   * Never cache card redirect decisions
   * =======================================================
   *
   * This applies to successful redirects AND temporary
   * subscription/configuration failures.
   *
   * Otherwise a browser/proxy could cache an old outcome.
   */
  res.setHeader(
    "Cache-Control",
    "no-store, no-cache, must-revalidate, proxy-revalidate"
  );

  res.setHeader(
    "Pragma",
    "no-cache"
  );

  res.setHeader(
    "Expires",
    "0"
  );

  try {
    /*
     * Destination resolution remains mandatory.
     *
     * Analytics is optional.
     */
    const context =
      await getCardRedirectContext(
        req.params
          .code as string
      );

    /*
     * HEAD requests are often generated by:
     *
     * crawlers
     * preview tools
     * uptime checks
     * link inspectors
     *
     * They are not customer taps.
     *
     * Do not create visitor cookies or analytics rows.
     */
    if (
      req.method !==
      "HEAD"
    ) {
      const visitor =
        getOrCreateAnonymousVisitor(
          req,
          res
        );

      const source =
        getInteractionSource(
          req.query
            .source
        );

      try {
        await trackWithinBudget({
          cardId:
            context.cardId,

          storeId:
            context.storeId,

          businessId:
            context.businessId,

          visitorKey:
            visitor.visitorKey,

          source,

          metadata:
            getInteractionRequestMetadata(
              req
            ),
        });
      } catch {
        /*
         * This should be rare because
         * trackWithinBudget already absorbs
         * normal tracking failures.
         *
         * Still never break the redirect.
         */
        console.warn(
          "interaction_dropped",
          {
            reason:
              "tracking_unavailable",
          }
        );
      }
    }

    return res.redirect(
      302,
      context.googleReviewUrl
    );
  } catch (
    error
  ) {
    const code =
      error instanceof Error
        ? error.message
        : "";

    if (
      code ===
      "SUBSCRIPTION_UNAVAILABLE"
    ) {
      /*
       * Never reveal billing details
       * to the restaurant's customer.
       */
      return res.redirect(
        302,

        `${env.FRONTEND_URL}/review-unavailable`
      );
    }

    if (
      code ===
      "CARD_NOT_FOUND"
    ) {
      return res
        .status(404)
        .send(
          "ValYou card not found."
        );
    }

    if (
      [
        "CARD_NOT_ACTIVE",
        "CARD_NOT_ASSIGNED",
      ].includes(
        code
      )
    ) {
      return res
        .status(410)
        .send(
          "This ValYou card is currently unavailable."
        );
    }

    if (
      [
        "GOOGLE_REVIEW_URL_MISSING",
        "INVALID_GOOGLE_REVIEW_URL",
      ].includes(
        code
      )
    ) {
      return res
        .status(503)
        .send(
          "The review page for this location is temporarily unavailable."
        );
    }

    return next(
      error
    );
  }
}